version: "3"

services:

  gateone:
    image: satomic/gateone:http
    ports:
    - "8000:8000"
    hostname: kubectl
    networks:
    - kind
    volumes:
    - ssh_key:/root/.ssh/
    - ~/.kube/:/root/.kube/

  lab:
    image: satomic/cka_lab
    entrypoint: /opt/entry.bash
    ports:
      - 80:80
    networks:
    - kind
    environment:
      GATEONE_HTTP_SERVER: "172.26.0.1:8000"

networks:
  networks:
  kind:
    external: true
volumes:
  ssh_key: {}
